### PR TITLE
Report iperf3 UDP packet loss

### LINKED ISSUE #77: [RFE] UDP Packet loss
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
iperf3 emits a loss metric for UDP_STREAM, we should capture that as part of our metrics.

```
				"udp":	{
					"socket":	5,
					"start":	0,
					"end":	10.000084,
					"seconds":	10.000084,
					"bytes":	1586206720,
					"bits_per_second":	1268954716.7803791,
					"jitter_ms":	0.00566680509469367,
					"lost_packets":	19285,
					"packets":	1549030,
					"lost_percent":	1.2449726603100004,
					"out_of_order":	0,
					"sender":	true
				}

### PR DESCRIPTION
**Pull request by jtaleric**
### Description
iperf3 reports packet loss.

### Fixes
fixes #77

### CODE REVIEW

**Comment by SachinNinganure** [comment]
here is the result from my manual test run for iperf
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
|    RESULT TYPE    | DRIVER  |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES | AVG LOSSPERCENT |     AVG VALUE      |    95% CONFIDENCE INTERVAL     |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
| 📊 Stream Results | netperf | TCP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 3       | Nil             | 4934.783333 (Mb/s) | 4927.452419-4942.114248 (Mb/s) |
| 📊 Stream Results | iperf3  | TCP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 3       | 0.000000        | 3356.340053 (Mb/s) | 3214.892685-3497.787421 (Mb/s) |
| 📊 Stream Results | netperf | TCP_STREAM | 1           | false        | false   | 8192         | false     | 10       | 3       | Nil             | 4920.573333 (Mb/s) | 4850.021127-4991.125540 (Mb/s) |
| 📊 Stream Results | iperf3  | TCP_STREAM | 1           | false        | false   | 8192         | false     | 10       | 3       | 0.000000        | 4895.027541 (Mb/s) | 4842.028485-4948.026598 (Mb/s) |
| 📊 Stream Results | netperf | UDP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 3       | Nil             | 1469.616667 (Mb/s) | 1446.487192-1492.746141 (Mb/s) |
| 📊 Stream Results | iperf3  | UDP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 3       | 1.098247        | 1521.110101 (Mb/s) | 1507.412400-1534.807803 (Mb/s) |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
+---------------+---------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
|  RESULT TYPE  | DRIVER  | SCENARIO | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES | AVG LOSSPERCENT |     AVG VALUE      |    95% CONFIDENCE INTERVAL     |
+---------------+---------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
| 📊 Rr Results | netperf | TCP_RR   | 1           | false        | false   | 1024         | false     | 10       | 3       | Nil             | 4277.390000 (OP/s) | 4063.999870-4490.780130 (OP/s) |
| 📊 Rr Results | netperf | TCP_CRR  | 1           | false        | false   | 1024         | false     | 10       | 3       | Nil             | 1876.583333 (OP/s) | 1846.057431-1907.109235 (OP/s) |
| 📊 Rr Results | netperf | TCP_CRR  | 1           | false        | true    | 1024         | false     | 10       | 3       | Nil             | 1816.123333 (OP/s) | 1794.586471-1837.660196 (OP/s) |
+---------------+---------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------------+--------------------+--------------------------------+
+--------------------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-------------------+
|    RESULT TYPE     | SCENARIO | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES | AVG 99%TILE VALUE |
+--------------------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-------------------+
| RR Latency Results | TCP_RR   | 1           | false        | false   | 1024         | false     | 10       | 3       | 268.000000 (usec) |
| RR Latency Results | TCP_CRR  | 1           | false        | false   | 1024         | false     | 10       | 3       | 610.666667 (usec) |
| RR Latency Results | TCP_CRR  | 1           | false        | true    | 1024         | false     | 10       | 3       | 626.666667 (usec) |
+--------------------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+-------------------+

**Comment by SachinNinganure** [comment]
It rightly reports avg_loss percent for iperf against Stream_Results.
Some other queries I have  for iperf tests 
1>**Stream_Results** result-type alone has a value for iperf  , so should we still keep **Rr_Results** and **RR_Latency_Results** for iperf tests, additionally the later result_types do not have the **iperf** driver_type aswell
2>is it easy to get TCP packet_loss percent

**Comment by jtaleric** [comment]
> It rightly reports avg_loss percent for iperf against Stream_Results. Some other queries I have for iperf tests 1>**Stream_Results** result-type alone has a value for iperf , so should we still keep **Rr_Results** and **RR_Latency_Results** for iperf tests, additionally the later result_types do not have the **iperf** driver_type aswell 2>is it easy to get TCP packet_loss percent

TCP Packet Loss? Do you mean TCP Retransmits?

**Comment by SachinNinganure** [comment]
yes the retransmits

**Comment by jtaleric** [comment]
Cleaned up output 

```+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------------+
|    RESULT TYPE    | DRIVER  |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES |     AVG VALUE      |    95% CONFIDENCE INTERVAL     |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------------+
| 📊 Stream Results | netperf | UDP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 5510.046667 (Mb/s) | 5259.322547-5760.770786 (Mb/s) |
| 📊 Stream Results | iperf3  | UDP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 3778.567851 (Mb/s) | 3776.457029-3780.678673 (Mb/s) |
| 📊 Stream Results | netperf | TCP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 4351.293333 (Mb/s) | 4188.087466-4514.499200 (Mb/s) |
| 📊 Stream Results | iperf3  | TCP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 4966.358955 (Mb/s) | 1142.159885-8790.558025 (Mb/s) |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------------+
+---------------------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+------------+
|        TYPE         |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES | AVG VALUE  |
+---------------------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+------------+
| UDP Loss Percent    | UDP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 0.099171   |
| TCP Retransmissions | TCP_STREAM | 2           | false        | false   | 1024         | false     | 10       | 3       | 219.333333 |
+---------------------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+------------+

**Comment by vishnuchalla** [comment]
Do we also report TCP packet loss and retransmits for netperf as well?

**Comment by jtaleric** [comment]
@vishnuchalla wanna re-review please.

**Pull request merged**
