### PR TITLE
Integrating go-commons prometheus client

### PR DESCRIPTION
**Pull request by vishnuchalla**
### Description
Integrating go-commons prometheus client
Prerequisite PR: https://github.com/cloud-bulldozer/go-commons/pull/8
We will change the import once the prerequisite PR is merged and cut a new release. Thanks!

### Tested in local environment
```
[vchalla@vchalla k8s-netperf]$ ./bin/amd64/k8s-netperf --search https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443
INFO[2023-05-26 08:28:56] 📒 Reading netperf.yml file.                  
INFO[2023-05-26 08:28:57] 🔬 openshift-monitoring namespace found       
WARN[2023-05-26 08:28:58] ⚠️  Single node per zone                     
INFO[2023-05-26 08:28:58] Deploying in us-west-2c zone                 
INFO[2023-05-26 08:28:58] ♻️  Using existing Service                   
INFO[2023-05-26 08:28:58] ♻️  Using existing Service                   
INFO[2023-05-26 08:28:58] ♻️  Using existing Deployment                
INFO[2023-05-26 08:28:58] ⏰ Checking for client-across Pods to become ready... 
INFO[2023-05-26 08:28:59] ♻️  Using existing Deployment                
INFO[2023-05-26 08:28:59] ⏰ Checking for server Pods to become ready... 
INFO[2023-05-26 08:29:00] 🗒️  Running netperf TCP_STREAM (service false) for 10s 
INFO[2023-05-26 08:29:14] 📁 Creating indexer: opensearch               
INFO[2023-05-26 08:29:15] Connected to : https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443 
INFO[2023-05-26 08:29:15] Indexing [1] documents in k8s-netperf        
INFO[2023-05-26 08:29:15] Indexing finished in 123ms: created=1        
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------+
|    RESULT TYPE    | DRIVER  |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES |     AVG VALUE      | 95% CONFIDENCE INTERVAL  |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------+
| 📊 Stream Results | netperf | TCP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 1       | 4865.140000 (Mb/s) | 0.000000-0.000000 (Mb/s) |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------+
+---------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------+
|        TYPE         | DRIVER  |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES | AVG VALUE |
+---------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------+
| TCP Retransmissions | netperf | TCP_STREAM | 1           | false        | false   | 1024         | false     | 10       | 1       | 2.000000  |
+---------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+-----------+

```

### CODE REVIEW

**Comment by jtaleric** [comment]
@rsevilla87 can I get your eyes here for a review please.

**Comment by rsevilla87** [comment]
Can you make a separate PR to remove vendor?, that change is out of scope of the title of this PR

**Comment by vishnuchalla** [comment]
> @vishnuchalla can you send a separate PR to remove vendor?, that change is out of scope of the title of this PR and makes reviewing more challenging

Changed as suggested. Will take vendor files removal in a separate PR.

**Review by jtaleric — APPROVED** [review]
LGTM!

**Pull request merged**
